name: Generate changelog
on:
  # release:
  #   types: [created, edited, published]
  pull_request:
    types: [closed]
  issues:
    types: [closed]
  workflow_run:
    workflows: ["Create release"]  # release.yml의 name과 일치해야 함
    types:
      - completed
  workflow_dispatch:  
  
permissions: 
  contents: write
  pull-requests: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Generate changelog
      uses: janheinrichmerker/action-github-changelog-generator@v2.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        futureRelease: ${{ github.event.release.tag_name || env.LATEST_TAG }}
        excludeTagsRegex: "^v[0-9]$"
        output: CHANGELOG.md
        repo: "eryajf/eryajfctl"
        unreleased: true
        issues: true
        pullRequests: true
        includeLabels: "bug,enhancement,feature"
        simpleList: true

    - name: Git Commit and Push
      uses: somaz94/go-git-commit-action@v1
      with:
        branch: main
        commit_message: "Update changelog"
        user_email: "actions@github.com"
        user_name: "GitHub Actions"
        file_pattern: "CHANGELOG.md"